### ISSUE TITLE
error: failed to define function org-ol-tree/display-sections

### ISSUE THREAD

**Issue by mediapathic** [Townk/org-ol-tree#11]
Since the latest-but-one update, whenever I try to run org-ol-tree I get 

```
apply: Autoloading file /Users/mediapathic/.emacs.d/.local/straight/build-27.1/org-ol-tree/org-ol-tree.elc failed to define function org-ol-tree/display-sections
```
And nothing else happens. 

I just ran an update (2021-03-31) and still have the issue. 

I'm assuming this is a local configuration issue, but have no idea how to proceed.

**Comment by Townk** [comment]
Remove the compiled files for `org-ol-tree`:

```sh
$ rm -f ~/.config/emacs/.local/straight/build-*/org-ol-tree/org-ol-tree.elc
```
or if your config is on your home folder:

```sh
$ rm -f ~/.emacs.d/.local/straight/build-*/org-ol-tree/org-ol-tree.elc
```
And change your mapping to call `org-ol-tree` instead of `org-ol-tree/display-sections`.

I removed the later for a better standardization.

Let me know if these steps fixed your problem.

**Comment by mediapathic** [comment]
Sorry for the delay -- yes, the update fixed this. And thanks for the heads up on the mapping as well.
