### ISSUE TITLE
Title is using file name full path when there is no `#+TITLE:` on the file

### ISSUE THREAD

**Issue by Townk** [Townk/org-ol-tree#8]
The root label function should use just the base file name as title (see [file-name-base](https://www.gnu.org/software/emacs/manual/html_node/elisp/File-Name-Components.html)).

Also, if the `TITLE` property is set, but the title is an empty string, it should also fall back to the file name title.

**Comment by Jake-Moss** [comment]
Even with `#+TITLE:` set file path is still used 
![image](https://user-images.githubusercontent.com/49361082/111986026-1e33e600-8b59-11eb-9655-2486509b76fc.png)

**Comment by Townk** [comment]
I believe the last commit fixed this.

The problem existed because I forgot to add a `#` character before the `+` 🤦🏻‍♂️.

If you can update your config and give it another try, let me know if it indeed got fixed.

**Comment by Townk** [comment]
Close the wrong bug!

**Comment by Jake-Moss** [comment]
Latest commit has fixed this, thank you!
