### ISSUE TITLE
Behavior is inconsistent with split windows

### ISSUE THREAD

**Issue by mediapathic** [Townk/org-ol-tree#9]
I like to have my working document vertically split with a separate buffer of notes. When I activate a header in the outline, usually both windows get populated with the resulting buffer (bad), sometimes it is one or the other (better, still bad). I'd like to be able to consistently  predict this so I can use more than one window in a frame with the outline.

(I recognize that this is probably in the deep dark hole of Emacs Window Positioning Hell, but figured it was worth asking.)

**Comment by Townk** [comment]
I think I know a way to fix that. Will try to get a patch to it shortly.
